name: Documentation

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=3 pip
          --file requirements.txt
          --file docs/requirements.txt
          --channel conda-forge

    - name: Install ioos_qc
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Build documentation
      run: >
        set -e
        pushd docs
        make clean html linkcheck
        popd

    - name: Deploy
      if: success() && github.event_name == 'release'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
