name: Full Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        numba: [true, false]
        # Numba is not out on Python 3.13 yet.
        exclude:
          - python-version: "3.13"
            numba: true
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Micromamba ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=${{ matrix.python-version }} pip
          --file requirements.txt
          --file requirements-dev.txt
          --channel conda-forge

    - name: Install ioos_qc
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: numba
      if: ${{ matrix.numba }}
      run: |
        micromamba install numba

    - name: Tests
      run: |
        python -m pytest --disable-warnings
